package main

type AutoGenerated struct {
	Type       string  `json:"_type"`
	Doc        any     `json:"Doc"`
	Package    any     `json:"Package"`
	Name       Name    `json:"Name"`
	Decls      []Decls `json:"Decls"`
	Imports    any     `json:"Imports"`
	Unresolved any     `json:"Unresolved"`
	Comments   any     `json:"Comments"`
	FileSet    FileSet `json:"FileSet"`
}
type Name struct {
	Type string `json:"_type"`
	Name string `json:"Name"`
}
type Path struct {
	Type  string `json:"_type"`
	Kind  string `json:"Kind"`
	Value string `json:"Value"`
}
type Specs struct {
	Type string `json:"_type"`
	Name any    `json:"Name"`
	Path Path   `json:"Path"`
}
type Params struct {
	Type string `json:"_type"`
	List any    `json:"List"`
}
type Type0 struct {
	Type       string `json:"_type"`
	TypeParams any    `json:"TypeParams"`
	Params     Params `json:"Params"`
	Results    any    `json:"Results"`
}
type LHS struct {
	Type string `json:"_type"`
	Name string `json:"Name"`
}
type Elt struct {
	Type string `json:"_type"`
	Name string `json:"Name"`
}
type Type0 struct {
	Type string `json:"_type"`
	Len  any    `json:"Len"`
	Elt  Elt    `json:"Elt"`
}
type Elts struct {
	Type  string `json:"_type"`
	Kind  string `json:"Kind"`
	Value string `json:"Value"`
}
type RHS struct {
	Type       string `json:"_type"`
	Type0      Type0  `json:"Type"`
	Elts       []Elts `json:"Elts"`
	Incomplete bool   `json:"Incomplete"`
}
type Key struct {
	Type string `json:"_type"`
	Name string `json:"Name"`
}
type X struct {
	Type string `json:"_type"`
	Name string `json:"Name"`
}
type Sel struct {
	Type string `json:"_type"`
	Name string `json:"Name"`
}
type Fun struct {
	Type string `json:"_type"`
	X    X      `json:"X"`
	Sel  Sel    `json:"Sel"`
}
type Args struct {
	Type string `json:"_type"`
	Name string `json:"Name"`
}
type X0 struct {
	Type string `json:"_type"`
	Fun  Fun    `json:"Fun"`
	Args []Args `json:"Args"`
}
type List struct {
	Type  string `json:"_type"`
	LHS   []LHS  `json:"Lhs,omitempty"`
	Tok   string `json:"Tok,omitempty"`
	RHS   []RHS  `json:"Rhs,omitempty"`
	Key   Key    `json:"Key,omitempty"`
	Value any    `json:"Value,omitempty"`
	X     X      `json:"X,omitempty"`
	Body  Body   `json:"Body,omitempty"`
	X0    X0     `json:"X,omitempty"`
}
type Body struct {
	Type string `json:"_type"`
	List []List `json:"List"`
}
type Decls struct {
	Type  string  `json:"_type"`
	Tok   string  `json:"Tok,omitempty"`
	Specs []Specs `json:"Specs,omitempty"`
	Recv  any     `json:"Recv,omitempty"`
	Name  Name    `json:"Name,omitempty"`
	Type0 Type0   `json:"Type,omitempty"`
	Body  Body    `json:"Body,omitempty"`
}
type Files struct {
	Name  string `json:"Name"`
	Base  int    `json:"Base"`
	Size  int    `json:"Size"`
	Lines []int  `json:"Lines"`
	Infos any    `json:"Infos"`
}
type FileSet struct {
	Base  int     `json:"Base"`
	Files []Files `json:"Files"`
}
