package main

type AutoGenerated struct {
	Type       string  `json:"_type"`
	Doc        any     `json:"Doc"`
	Package    any     `json:"Package"`
	Name       Name    `json:"Name"`
	Decls      []Decls `json:"Decls"`
	Imports    any     `json:"Imports"`
	Unresolved any     `json:"Unresolved"`
	Comments   any     `json:"Comments"`
	FileSet    FileSet `json:"FileSet"`
}
type Name struct {
	Type string `json:"_type"`
	Name string `json:"Name"`
}
type Path struct {
	Type  string `json:"_type"`
	Kind  string `json:"Kind"`
	Value string `json:"Value"`
}
type Specs struct {
	Type string `json:"_type"`
	Name any    `json:"Name"`
	Path Path   `json:"Path"`
}
type Names struct {
	Type string `json:"_type"`
	Name string `json:"Name"`
}
type Type0 struct {
	Type string `json:"_type"`
	Name string `json:"Name"`
}
type List struct {
	Type  string  `json:"_type"`
	Names []Names `json:"Names"`
	Type0 Type0   `json:"Type"`
}
type Params struct {
	Type string `json:"_type"`
	List []List `json:"List"`
}
type Type0 struct {
	Type       string `json:"_type"`
	TypeParams any    `json:"TypeParams"`
	Params     Params `json:"Params"`
	Results    any    `json:"Results"`
}
type X struct {
	Type string `json:"_type"`
	Name string `json:"Name"`
}
type Sel struct {
	Type string `json:"_type"`
	Name string `json:"Name"`
}
type Fun struct {
	Type string `json:"_type"`
	X    X      `json:"X"`
	Sel  Sel    `json:"Sel"`
}
type X struct {
	Type  string `json:"_type"`
	Kind  string `json:"Kind"`
	Value string `json:"Value"`
}
type Y struct {
	Type string `json:"_type"`
	Name string `json:"Name"`
}
type Args struct {
	Type string `json:"_type"`
	X    X      `json:"X"`
	Op   string `json:"Op"`
	Y    Y      `json:"Y"`
}
type X struct {
	Type string `json:"_type"`
	Fun  Fun    `json:"Fun"`
	Args []Args `json:"Args"`
}
type List struct {
	Type string `json:"_type"`
	X    X      `json:"X"`
}
type Body struct {
	Type string `json:"_type"`
	List []List `json:"List"`
}
type Decls struct {
	Type  string  `json:"_type"`
	Tok   string  `json:"Tok,omitempty"`
	Specs []Specs `json:"Specs,omitempty"`
	Recv  any     `json:"Recv,omitempty"`
	Name  Name    `json:"Name,omitempty"`
	Type0 Type0   `json:"Type,omitempty"`
	Body  Body    `json:"Body,omitempty"`
}
type Files struct {
	Name  string `json:"Name"`
	Base  int    `json:"Base"`
	Size  int    `json:"Size"`
	Lines []int  `json:"Lines"`
	Infos any    `json:"Infos"`
}
type FileSet struct {
	Base  int     `json:"Base"`
	Files []Files `json:"Files"`
}
