package main

type AutoGenerated struct {
	Type       string  `json:"_type"`
	Doc        any     `json:"Doc"`
	Package    any     `json:"Package"`
	Name       Name    `json:"Name"`
	Decls      []Decls `json:"Decls"`
	Imports    any     `json:"Imports"`
	Unresolved any     `json:"Unresolved"`
	Comments   any     `json:"Comments"`
	FileSet    FileSet `json:"FileSet"`
}
type Name struct {
	Type string `json:"_type"`
	Name string `json:"Name"`
}
type Params struct {
	Type string `json:"_type"`
	List any    `json:"List"`
}
type Type0 struct {
	Type       string `json:"_type"`
	TypeParams any    `json:"TypeParams"`
	Params     Params `json:"Params"`
	Results    any    `json:"Results"`
}
type Fun struct {
	Type string `json:"_type"`
	Name string `json:"Name"`
}
type Args struct {
	Type  string `json:"_type"`
	Kind  string `json:"Kind"`
	Value string `json:"Value"`
}
type X struct {
	Type string `json:"_type"`
	Fun  Fun    `json:"Fun"`
	Args []Args `json:"Args"`
}
type List struct {
	Type string `json:"_type"`
	X    X      `json:"X"`
}
type Body struct {
	Type string `json:"_type"`
	List []List `json:"List"`
}
type Decls struct {
	Type  string `json:"_type"`
	Recv  any    `json:"Recv"`
	Name  Name   `json:"Name"`
	Type0 Type0  `json:"Type"`
	Body  Body   `json:"Body"`
}
type Files struct {
	Name  string `json:"Name"`
	Base  int    `json:"Base"`
	Size  int    `json:"Size"`
	Lines []int  `json:"Lines"`
	Infos any    `json:"Infos"`
}
type FileSet struct {
	Base  int     `json:"Base"`
	Files []Files `json:"Files"`
}
